project_id = "luhbkhosuawobupmzzrv"

[functions.bulk-upload-inventory]
verify_jwt = true

[functions.complete-sale]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.gdpr-request]
verify_jwt = true

[functions.list-users]
verify_jwt = true
